sonar.projectKey=ARK-Software-Team_BookTrack
sonar.organization=ark-software-team
sonar.projectName=BookTrack
sonar.projectVersion=1.0
sonar.sources=lib
sonar.exclusions=**/*.g.dart,**/firebase_options.dart
sonar.dart.file.suffixes=.dart